### ISSUE TITLE
Question on Relations

### ISSUE THREAD

**Issue by alecrae** [dohomi/storyblok-generate-ts#1]
First off, thank you for the fantastic utility! It's been helpful as I've been learning about storyblok.

In regards to referencing components (ie global components) which are resolved by the `resolve_relations` query string, Is there a way to link the types based on the reference? At the moment the generated type for a reference field is a string (for the UUID)

**Comment by dohomi** [comment]
@alecrae thanks for your kind words. 

I honestly never digged into `resolove_relations` for generating TS interfaces? Can you elaborate how that would look like when you place a console log? You can add a custom parser to your script like shown in this example:
https://github.com/dohomi/storyblok-generate-ts#example-custom-parser
The field name would be your relation and then we can see how that would look like and we can built it into the main script

**Comment by dohomi** [comment]
@alecrae I solved this now with a simple type extend:
```ts
type PageWithRelations = PageStoryblok & {
  author?: StoryData<AuthorStoryblok>
  categories?: StoryData<CategoryStoryblok>[]
  tags?: StoryData<TagStoryblok>[]
}
```
I don't think it's necessary to do anything in the generator function.
