### ISSUE TITLE
Multiple exports of name 'TableStoryblok'

### ISSUE THREAD

**Issue by tomsansome** [dohomi/storyblok-generate-ts#12]
Hey, thanks for this tool, very helpful 🙏 

**Issue:**
- We have a component called `table` with the field `data` inside which is of type `Table`
<img width="452" alt="Screenshot 2022-07-26 at 16 47 50" src="https://user-images.githubusercontent.com/1481506/181051476-3737e267-91c8-41d1-92a1-b9674ad87d14.png">

- When we generate the types we end up with:

```
export interface TableStoryblok {
    thead: {
        _uid: string;
        value?: string;
        component: number;
        [k: string]: any;
    }[];
    tbody: {
        _uid: string;
        body: {
            _uid?: string;
            value?: string;
            component?: number;
            [k: string]: any;
        }[];
        component: number;
        [k: string]: any;
    }[];
    [k: string]: any;
}

export interface TableStoryblok {
    data?: TableStoryblok;
    _uid: string;
    component: 'table';
    [k: string]: any;
}
```

This has generated `TableStoryblok` twice in our generated file.

We _could_ rename this `table` component to something like `ourTable`, but would like to avoid having to do this just for this situation.

Any ideas with this one? Does this look like a bug?

Thanks again 🙏

**Comment by dohomi** [comment]
Hi @tomsansome I would not use the name "table" this seems like it has naming conflict with the built in table component from Storyblok: https://github.com/dohomi/storyblok-generate-ts/pull/11

**Comment by tomsansome** [comment]
Thanks for the help @dohomi 🙏
