### ISSUE TITLE
Names of generated types sometimes inconsistent

### ISSUE THREAD

**Issue by jbeast** [dohomi/storyblok-generate-ts#19]
Hi, thanks again for the useful tool.

I've come across an issue with the types of components when referenced inside another component, sometimes does not match the actual component's name.

For example, when using this stripped down version of `components.json`:

```json
{
  "components": [
    {
      "name": "ConversationTemplate",
      "display_name": "Conversation Template",
      "id": 1530302,
      "schema": {
        "characters": {
          "type": "bloks",
          "restrict_components": true,
          "component_whitelist": [
            "ConversationTemplate__character"
          ],
          "required": true,
          "pos": 0,
          "description": "Set how many characters will be part of the conversation."
        }
      }
    },
    {
      "name": "ConversationTemplate__character",
      "display_name": "Character",
      "created_at": "2021-05-11T13:56:11.271Z",
      "updated_at": "2022-08-10T08:57:12.313Z",
      "id": 1530304,
      "schema": {
        "name": {
          "type": "text",
          "required": true,
          "max_length": "50",
          "description": "Character name will appear onscreen to the learner and can be specific (e.g., Dale's mum, Nisha) or generic (e.g. Doctor). "
        }
      }
    }
  ]
}
```

It generates:

```typescript
export interface ConversationTemplateStoryblok {
  characters: ConversationTemplateCharacterStoryblok[]; // <-- No underscore
  _uid: string;
  component: "ConversationTemplate";
  [k: string]: any;
}

export interface ConversationTemplate_CharacterStoryblok {
  name: string;
  _uid: string;
  component: "ConversationTemplate__character";
  [k: string]: any;
}
```

One way of fixing this would be for the components in Storyblok not to have the double underscore. However, sadly the naming of the components is not always within my control.

From looking at the code, it seems like sometimes the type's title is generated with:

```typescript
getTitle(values.name)
```

and other times:

```typescript
camelcase(getTitle(value.name), {
  pascalCase: true
})
```

which I think is leading to the inconsistency.

I was thinking about putting in a PR, but thought it may be best to check with you first, as there may be a reason the 2 different methods are used. Plus this change may be a breaking one for some people.

Would be interested to hear your thoughts!

Best regards,
Chris

**Comment by dohomi** [comment]
Hi @jbeast  I'm happy to merge any PR but it would be great if its non-breaking. I honestly never came across this particular issue.

**Comment by LeanderG** [comment]
First off, also big thanks for this useful tool.
I found another name inconsistency. A component named CTA with all capital letters has the interface `CTAStoryblok` but other interfaces use `CtaStoryblok`.

Json:
```json
{
  "components": [
    {
      "name": "CTA",
      "display_name": null,
      "created_at": "2023-01-30T14:00:19.582Z",
      "updated_at": "2023-01-30T14:12:00.555Z",
      "id": 3367792,
      "schema": {
        "text": {
          "type": "text",
          "key": "text",
          "pos": 0
        }
      },
      "preview_field": null,
      "is_root": false,
      "preview_tmpl": null,
      "is_nestable": true,
      "all_presets": [],
      "preset_id": null,
      "real_name": "CTA",
      "component_group_uuid": null,
      "color": null,
      "icon": null
    },
    {
      "name": "feature",
      "display_name": null,
      "created_at": "2023-01-30T10:42:08.215Z",
      "updated_at": "2023-01-30T14:47:20.390Z",
      "id": 3366737,
      "schema": {
        "CTA": {
          "type": "bloks",
          "restrict_type": "",
          "restrict_components": true,
          "component_whitelist": ["CTA"],
          "maximum": 1
        }
      },
      "preview_field": null,
      "is_root": false,
      "preview_tmpl": null,
      "is_nestable": true,
      "all_presets": [],
      "preset_id": null,
      "real_name": "feature",
      "component_group_uuid": null,
      "color": null,
      "icon": null
    }
  ]
}
```
Generated TypeScript:
```typescript
import { StoryblokStory } from "storyblok-generate-ts";

export interface CTAStoryblok { // <--
  text?: string;
  _uid: string;
  component: "CTA";
  [k: string]: any;
}

export interface FeatureStoryblok {
  CTA?: CtaStoryblok[]; // <-- 
  _uid: string;
  component: "feature";
  [k: string]: any;
}
```

**Comment by dohomi** [comment]
@jbeast please let me know how I could assist.. would it make sense to introduce a generic name function inside of the options?

**Comment by yobananaboy15** [comment]
I also have this issue, but I'm confused about what is causing it. Is preserveConsecutiveUppercase: true on in the camelcase options a possible solution?

**Comment by LeanderG** [comment]
One possible solution would be to replace this line:
https://github.com/dohomi/storyblok-generate-ts/blob/6da7add35278c836d9fbe5e4df2a91659d40394b/src/index.ts#L50
with this line:
`title: camelcase(getTitle(values.name), {pascalCase: true}),`

The interface would then always have the same name as the property, fixing the bug. Unfortunately, this would be a breaking change.

@dohomi If you are ok with this solution, I can create a PR.

**Comment by dohomi** [comment]
would this change change the default of how labels are created? if not - I guess many users are just using the default - then it would not be a big of deal. I honestly never came across inconsistency in the naming

**Comment by LeanderG** [comment]
It would change the interface labels that contain underscores or uppercase letters next to each other. Let's look at my and @jbeast's examples:

Right now a blok with name `CTA` has the interface `CTAStoryblok`. With the above change it would be `CtaStoryblok`.

A blok with name `ConversationTemplate__character` has the interface `ConversationTemplate_CharacterStoryblok`. After the above change it would be `ConversationTemplateCharacterStoryblok`.

Most interface labels should be unchanged though.

**Comment by dohomi** [comment]
how about enabling the new conversion via compiler option? That way  its non-breaking and users can opt-in

**Comment by Kiewiet1024** [comment]
Hi @dohomi, we also stumbled upon this becoming an issue when want to update nuxt to 3.7.0 or above and it is also capitals next to each other in the naming. Coincidently `CTA` as well. I understand the situation of it maybe breaking other scenarios, will be much appreciated if there can be a compiler option as you mentioned

**Comment by dohomi** [comment]
I think the best to solve it is a compiler option to use the `pascalCase`, this way we can optIn and it would not be a breaking change

**Comment by dohomi** [comment]
I bumped v2 now with this change, now the getTitle function uses `camelcase`. Please let me know if this resolves this issue.

**Comment by Kiewiet1024** [comment]
@dohomi, thank you for the change and will revert here if it is not working. Thanks again for the package and still maintaining it
