### ISSUE TITLE
Any reason date fields not supported?

### ISSUE THREAD

**Issue by cronin4392** [dohomi/storyblok-generate-ts#2]
I noticed that date fields are not parsed. Any reason? Not sure if it would be as easy as just adding to [this list](https://github.com/dohomi/storyblok-generate-ts/blob/master/src/index.js#L176)?

**Comment by dohomi** [comment]
@cronin4392 date fields are not parsed because I haven't used them yet. would you think they should be parsed as date object or rather a string? Feel free to open a PR

**Comment by dohomi** [comment]
fixed in #3

**Comment by dohomi** [comment]
@ValterSantosMatos @cronin4392 I updated to v.1.1.1 where you can use this script as CLI script. this might make it easier for you guys to use it. Let me know if you bump into issues
