### ISSUE TITLE
Why is multi-options field of type `(number | string)[]`?

### ISSUE THREAD

**Issue by peperoli** [dohomi/storyblok-generate-ts#26]
In Storyblok I have a component with multi-options field called `tags`. Its source is a Storyblok data source. Data sources usually are key-value pairs where the key is a string so what I would expect is that `tags` are typed as `string[]` but instead I get the following:

```ts
export interface ExampleStoryblok {
  headline?: string;
  tags?: (number | string)[];
  text?: any;
  _uid: string;
  [k: string]: any;
}
```

Is there a case which I'm not thinking about where a multi-option field with internal source uses numbers?

PS: Thanks a lot for mantaining this repo, it is very useful!

**Comment by dohomi** [comment]
@peperoli multi-options seems to be able to provide numbers as well. I haven't done any more research on it, but on the coding side of things I usually just use them as strings.

**Comment by schaschjan** [comment]
@peperoli Data sources can also return numbers. I think Storyblok changed that behaviour to return anything as string at some point, but I spotted this on an older project and the values are still numbers or strings, so data created prior to that change has not been migrated.

**Comment by peperoli** [comment]
Alright, that's good to know. Thanks for your answers!
