### ISSUE TITLE
Unused import when generated via cli

### ISSUE THREAD

**Issue by plumber-dhaval** [dohomi/storyblok-generate-ts#27]
In the latest version when i generate via cli i get an unused import at the top of the file. This did not happen in prior versions.

The unused import is:
`import {StoryblokStory} from 'storyblok-generate-ts'`

**Comment by schaschjan** [comment]
The `StoryblokStory` type is required in modeling relations between content types. Your Storyblok project does not seem to use any, that is why the import remains unused. There could be checked if there are any relations in the project, and if not omitting the import. However I find the effort for implementing this not really worth it, but your contribution would be welcomed.

**Comment by dohomi** [comment]
any PR is welcome but otherwise I just don't have a component structure without StoryblokStory so I haven't seen the unused import..
