### ISSUE TITLE
What about the `[k: string]: any;` in every type definition

### ISSUE THREAD

**Issue by tafelnl** [dohomi/storyblok-generate-ts#31]
First of all: thank you for this tool. I've discovered it recently, and it's very promising. Keep up the good work.

---

Every type seems to have a `[k: string]: any;` part attached to it. I'm not sure why though. It partly renders the type definitions useless, as mistakes like these, will go unnoticed:

Imagine we have the following type:

```ts
// component-types-sb.d.ts
export interface TestimonialStoryblok {
  title?: string;
  content?: any;
  _uid: string;
  component: "Testimonial";
  [k: string]: any;
}
```

Then in the application we do something like this:

```vue
<p>
  {{ blok.subtitle }}
</p>
```

It won't throw a type error, although we already know `subtitle` does not exist on `TestimonialStoryblok`.

**Comment by tafelnl** [comment]
After a bit more reading I guess that's what `unknownAny` is for right?

Related to this: https://github.com/bcherny/json-schema-to-typescript/issues/153 and https://github.com/bcherny/json-schema-to-typescript/issues/275

Still, maybe it makes sense to not include this in this library, because I think for this library it doesn't really make sense to include a `[k: string]: any;` or even a `[k: string]: unknown;`

**Comment by dohomi** [comment]
@tafelnl you can switch off the `unknownAny ` thats what that compilerOption is for. I won't change the default for now as every developer has its own preference.
