### ISSUE TITLE
Improve typing of rich text fields

### ISSUE THREAD

**Issue by cjpearson** [dohomi/storyblok-generate-ts#36]
Currently rich text fields are typed as `any`. Would it be possible to use the `Richtext` interface from `storyblok-js-client` instead? 

```
export interface Richtext {
  content: Array<Object>;
}
``` 

It's small, so perhaps it could also be done inline?

**Comment by dohomi** [comment]
Thanks for raising this issue. Any PR welcome

**Comment by Kuboczoch** [comment]
Seems like #42 is ready to be merged. Can you @dohomi publish it?
