### ISSUE TITLE
Why does MultilinkStoryblok provide `linktype?: string`

### ISSUE THREAD

**Issue by wweaver** [dohomi/storyblok-generate-ts#38]
For me using the `MultilinkStoryblok` is hard to use because there's no way to get out of this type because linktype blankets all strings
```typescript
  | {
      cached_url?: string;
      linktype?: string;
      [k: string]: any;
    }
```

https://github.com/dohomi/storyblok-generate-ts/blob/45fa291327cf6e3925dd985eda5fad6cae2c9408/example/component-types-sb-backup.d.ts#L256-L278

I would want to be able to do something like this

```typescript
if (blok.linktype === 'url') {
    return blok.url;
}
```

But it says `url` is `any` because the base type is also matched

![Cursor_and_frontend_–_helpers_ts](https://user-images.githubusercontent.com/1482976/226953145-cf036a75-9d7c-4a40-a462-6a55b4b980c0.png)

**Comment by dohomi** [comment]
@wweaver do you have any code example?

**Comment by wweaver** [comment]
@dohomi, nothing publicly available. The code example I have is what I shared. I can try to create a dummy project in the near future that shows it.

**Comment by dohomi** [comment]
you can also disable the unknown any feature flag: https://github.com/dohomi/storyblok-generate-ts#example

**Comment by dohomi** [comment]
Ideally Storyblok should enable type generation based on space ID's components. I just started this repo due to missing types when building my component API.

**Comment by wweaver** [comment]
> you can also disable the unknown any feature flag: https://github.com/dohomi/storyblok-generate-ts#example
> thats removing all [k:string]:any statements

omg I'm sorry, I misread your comment. I thought you were saying to switch any to unknown. If it's removing the `[k:string]:any|unknown` that's perfect. Sorry about that. I'll take a look.

**Comment by wweaver** [comment]
> Ideally Storyblok should enable type generation based on space ID's components. I just started this repo due to missing types when building my component API.

Thanks @dohomi. I just sent an email to our representative at storyblok with the concerns. Unfortunately I can't post here because it had some details in our code.

But the gist I had was this:

1. The biggest concern I had was that the types are all generated with a generic `[key: string]: any` (or `[key: string]: unknown]`) which to me makes these types hard to work with.
2. Another concern I had was with the `MultilinkStoryblok` defining a catchall type for `linktype?: string` which makes it much harder to narrow down the type you’re actually working with.


I also mentioned that having types like this would be beneficial

```typescript
export interface Story {
    name: string;
    created_at?: string;
    published_at?: string;
    id: number;
    uuid: string;
    content?: {
        [k: string]: any;
    };
    slug: string;
    full_slug: string;
    sort_by_date?: null | string;
    position?: number;
    tag_list?: string[];
    is_startpage?: boolean;
    parent_id?: null | number;
    meta_data?: null | {
        [k: string]: any;
    };
    group_id?: string;
    first_published_at?: string;
    release_id?: null | number;
    lang?: string;
    path?: null | string;
    alternates?: any[];
    default_full_slug?: null | string;
    translated_slugs?: null | any[];
}

export interface LinkStoryStoryblok {
    id?: string;
    cached_url?: string;
    anchor?: string;
    linktype?: 'story';
    story?: Story;
}

export interface LinkAssetStoryblok {
    url?: string;
    cached_url?: string;
    anchor?: string;
    linktype?: 'asset';
}

export interface LinkUrlStoryblok {
    url?: string;
    cached_url?: string;
    anchor?: string;
    linktype?: 'url';
}

export interface LinkEmailStoryblok {
    email?: string;
    linktype?: 'email';
}

export type MultilinkStoryblok = LinkStoryStoryblok | LinkAssetStoryblok | LinkUrlStoryblok | LinkEmailStoryblok;
```

With all story types being generated extending the `Story`

```typescript
export interface CustomStoryStoryblok extends Story {
    _uid: string;
    component: 'custom-story';
    ...
}
```

**Comment by wweaver** [comment]
Looking through your code and I do see you have a `StoryBlokStory<TContent>` interface that is the `Story` interface I mentioned, so that would work nicely I'd think.

**Comment by wweaver** [comment]
> you can also disable the unknown any feature flag: https://github.com/dohomi/storyblok-generate-ts#example thats removing all [k:string]:any statements

I see you can remove it with `compilerOptions.additionalProperties=false`.
