### ISSUE TITLE
Suggestion: add a default "customTypeParser" to the plugins library

### ISSUE THREAD

**Issue by ValterSantosMatos** [dohomi/storyblok-generate-ts#4]
Hi @dohomi , I was going to do another PR, but better ask first, so as an example I am using the `seo-metatags` plugin which has the following type bellow, everything works well however I was wondering if we should just add this to the library itself so no one else has to type/retype the custom plugin since it should be the same for everyone (you could for example overwrite it if needed).

Let me know if you want me to PR.
Ty
Valter 

```
 customTypeParser: function exampleCustomParser(key, obj) {
    switch (obj.field_type) {
      case 'seo-metatags':
        return {
          [key]: {
            type: 'object',
            properties: {
              _uid: {
                type: 'string'
              },
              title: {
                type: 'string'
              },
              plugin: {
                type: 'string'
              },
              og_image: {
                type: 'string'
              },
              og_title: {
                type: 'string'
              },
              description: {
                type: 'string'
              },
              twitter_image: {
                type: 'string'
              },
              twitter_title: {
                type: 'string'
              },
              og_description: {
                type: 'string'
              },
              twitter_description: {
                type: 'string'
              }
            }
          }
        }
      default:
        return {}
    }
  }
  ```

**Comment by dohomi** [comment]
I'd suggest we could have a custom parser in a small library? I don't use this plugin for example, but we could collect all snippets inside this repo and have some guidance how to use it, how does that sound?

**Comment by ValterSantosMatos** [comment]
Hi, up to you to be honest. My use case I have both a website and a mobile app so I need to copy the `exampleCustomParser` to both repos, hence the suggestion of adding it somewhere to the lib. This is the only plugin I am using so far.

**Comment by dohomi** [comment]
@ValterSantosMatos I published v.1.3.0 can you verify that this works for you? I added your custom parser als first start and we can extend the custom map further on.

**Comment by ValterSantosMatos** [comment]
Thanks, looks good 👍
