### ISSUE TITLE
Possible to generate types used in links endpoint?

### ISSUE THREAD

**Issue by jenseo** [dohomi/storyblok-generate-ts#43]
I'm using a folder structure inside Storyblok to set up a new FAQ, where the structure looks like the following:

```
Parent folder
    - Sub folder
        - Question
        - Question
    - Sub folder
        - Question
        - Question
        - Question
Parent folder
    - Sub folder
        - Question
```
...and so on. This to get unique slugs for each parent/sub folder/question, to make everything linkable.

I'm fetching the folders to set up the url structure in my project like this:

```
const customerFaq = await client.getAll('cdn/links', {
	version: "draft",
	starts_with: 'faq/customer/'
});
```

To filter the folders, I do like this:

`const customerFaqFolders = customerFaq.filter((item) => item.is_folder);`

Each of these folder entries looks like this:

```
{
    id: 12345678,
    slug: 'faq/customer/folder',
    name: 'Folder name',
    is_folder: true,
    parent_id: 23456789,
    published: false,
    path: null,
    position: 0,
    uuid: '12345678-1234-1234-1234-012345678910',
    is_startpage: false,
    real_path: '/faq/customer/folder'
}
```

...but it seems there are not types being generated for the folder structure, only for the Question stories inside the folders. 

Is it possible to set up typings for these kind of items, which are fetched with the `cdn/links` endpoint?

Thanks a lot for this awesome library, it has helped us a lot when working with Storyblok!

**Comment by dohomi** [comment]
does #41 might help you? I am very busy at work will try to bump out a new version very soon

**Comment by jenseo** [comment]
Hmm, interesting! Might do, need to look a bit closer on how the CLI works at storyblok! Thanks, appreciate you taking the time to answer!

**Comment by dohomi** [comment]
You might have confused what this library does: you fetch via storyblok CLI a component structure:
```sh
storyblok pull-components --space=[SPACE_ID]
```
This JSON file created you feed via step 3 described here: https://github.com/dohomi/storyblok-generate-ts#c-create-node-script-inside-of-your-packagejson-scripts

So there are no backend calls whatsoever inside of this library, it just parses JSON components from Storyblok and creates TypeScript definition files. Hope this helps you to deal with your task.

**Comment by dohomi** [comment]
closing this for now
