### ISSUE TITLE
Storyblok number field is a string in JSON response not a number 

### ISSUE THREAD

**Issue by davidhoeck** [dohomi/storyblok-generate-ts#44]
Currently the generated types are generic `number` but in reality numbers are a string in the json response: 
<img width="391" alt="image" src="https://github.com/dohomi/storyblok-generate-ts/assets/24294584/e66b5a06-6fba-4806-9a9e-a66d599c9705">

<img width="594" alt="image" src="https://github.com/dohomi/storyblok-generate-ts/assets/24294584/0a5c9908-ceb0-4f68-b181-03c25fd39a3d">

So I think we should switch to a `string` generic type instead to use `parseFloat` without any type-casting.

**Comment by dohomi** [comment]
I always wonder about this one: is this a flaw of Storyblok API? Or is this because the response can't handle integers?

**Comment by davidhoeck** [comment]
The first screenshot above is straight from the "Published JSON" link in the actions dropdown on the story edit view. I think it is a flaw 😓
