### ISSUE TITLE
Should numeric fields really have type string?

### ISSUE THREAD

**Issue by scmx** [dohomi/storyblok-generate-ts#46]
Hi 👋
I noticed the recent change "Parse numbers to string type" #45 to change numeric fields to have type string in the resulting interface.
This might not be correct. For me the numeric field values have always been given as number literals from api and storyblok-js-client.

Perhaps the data you looked at was a field that had type string and was changed to numeric, and there might be some bug resulting in you continuing to get it as a string because of the previous type?

Some ideas:
Maybe a jsdoc comment could be generated that shows the storyblok type of each field.

If we can verify that the value is sometimes a number then maybe consider having `string | number` as generated type.
Consumers would still need to wrap each usage with `Number(blok.field)` but at least you see that it might already be a string.

**Comment by dohomi** [comment]
As discussed in PR https://github.com/dohomi/storyblok-generate-ts/pull/45 @davidhoeck changed it to string. I am honestly not sure whats the right approach.. currently I cast a lot of string => number but its been a while since I worked with Storyblok

**Comment by davidhoeck** [comment]
I created a new number field and with every configuration the output was a string. So I don't think that Storyblok returns int or float values at all.

**Comment by davidhoeck** [comment]
An example: 

The JSON: 
<img width="262" alt="image" src="https://github.com/dohomi/storyblok-generate-ts/assets/24294584/011d3589-d84a-4e5c-bce3-40a76c22fe4a">

The Field: 
<img width="1208" alt="image" src="https://github.com/dohomi/storyblok-generate-ts/assets/24294584/cb4be0a7-ed64-4508-9cf2-927238913afa">

The Field config: 
<img width="480" alt="image" src="https://github.com/dohomi/storyblok-generate-ts/assets/24294584/341eea75-f779-4ac9-b46e-c42eae43b3c5">

**Comment by bilal1133** [comment]
Any progress on this, Please help.

**Comment by dohomi** [comment]
you have to manually cast your number fields inside your components from string => number. Thats currently the only way as the response from the Storyblok API is of type string.
