### ISSUE TITLE
Typescript error removal

### ISSUE THREAD

**Issue by ptiry02** [dohomi/storyblok-generate-ts#51]
Hi,
While developing a project with astro and storyblok in typescript I realized there is an error message I'm not able to remove unless I modify the component types file by hand.

![image](https://github.com/dohomi/storyblok-generate-ts/assets/97674049/812e8f3b-ff97-4a49-92c4-4ce6fc62255c)

I found out that I can remove the error by extending the component type from the SbBlokData type:

```javascript
export interface LocationGalleryStoryblok extends SbBlokData {
  [...]
}
```

Is there a way to add the 'extends' declaration with storyblok-generate-ts?

Thank you

**Comment by ptiry02** [comment]
Apparently, it's the argument type accepted for the "storyblokEditable" function.
![image](https://github.com/dohomi/storyblok-generate-ts/assets/97674049/f72eb918-9d3a-4178-8eb4-8362cebeb8bb)

I don't have that much experience with Typescript, but from what I understand, is that the generated types that are created from your library (which, by the way, is a great time saver and I love it 🤩) are missing the option to call the object with bracket notation.
![image](https://github.com/dohomi/storyblok-generate-ts/assets/97674049/f95607f4-2fcf-4301-bafe-862569d51472)

So, I can also get rid of the error message if I manually add this to the generated component types:
```javascript
[index: string]: string | number | object | boolean | undefined;
```

Would it be possible to have it added to the generated types? Or at least have it as an option?

Thank you

**Comment by dohomi** [comment]
I'd accapt any PR I honestly never bumped into this issue and also think the type of `storyblokEditable` could be adjusted to accept properly typed components

**Comment by ptiry02** [comment]
Hi @dohomi,
I just realized that a partner I'm working with added a script to the project that removes the line ```[k: string]: any;``` from every generated type which then produces the error 🤦‍♂️.

I'm sorry if I created any inconvenience.

Thank you and best regards!

**Comment by dohomi** [comment]
> Hi @dohomi, I just realized that a partner I'm working with added a script to the project that removes the line `[k: string]: any;` from every generated type which then produces the error 🤦‍♂️.
> 
> I'm sorry if I created any inconvenience.
> 
> Thank you and best regards!

Is that the compiler option unknownAny or probably set additionalProperties to false? https://github.com/dohomi/storyblok-generate-ts#compiler-options
