### ISSUE TITLE
Remove bundled dependencies from published package

### ISSUE THREAD

**Issue by Jtalk** [dohomi/storyblok-generate-ts#55]
Right now, this package's latest version in NPM includes:
- `example/node_modules` - the full set of dependencies for the example project.
- `.yarn/cache` - the PnP offline mirror, useful for development, not useful for publishing.

It drives the total size to 55MB zipped, which in turns generates warnings from Github when using Yarn's [Zero Installs](https://yarnpkg.com/features/caching#zero-installs).

It probably isn't intentional, and a simple [.npmignore](https://www.npmjs.com/package/npmignore) should fix it & prevent future re-occurrence.

<img width="523" alt="image" src="https://github.com/dohomi/storyblok-generate-ts/assets/1573833/e073cc06-e161-4f55-bac7-e22ce4e41b0c">

It might also be worth it to exclude the `.github` folder while we're at it, along with linter configs & tests. 

Thanks!

**Comment by dohomi** [comment]
any PR is welcome

**Comment by dohomi** [comment]
I published v2.0.1 with a `files` section in package.json. Does this fix your concern only publishing the `dist` folder on npm?

**Comment by Jtalk** [comment]
It looks great, thanks a lot!
