### ISSUE TITLE
Request fails when pulling components (code 401)

### ISSUE THREAD

**Issue by andrewchmr** [dohomi/storyblok-generate-ts#6]
**Summary of the bug:**

It is not possible to generate types because of a failing request (code 401)

<img width="753" alt="image" src="https://user-images.githubusercontent.com/43907473/167791716-946b02e5-3d92-4ac2-acf3-2147fc5422ea.png">

**Note:** It was working perfectly previously

**Reproduction path:**
- Run `storyblok pull-components --space=[SPACE_ID]`

**Expected behaviour:**
Types should be generated

**Actual behaviour:**
Error is thrown

**Comment by dohomi** [comment]
@andrewchmr logout out and login again. That has nothing to do with this plugin your authentication just expired

**Comment by andrewchmr** [comment]
> @andrewchmr logout out and login again. That has nothing to do with this plugin your authentication just expired

Thank you for quick reply! It helped 🙌
