### ISSUE TITLE
Custom Plugin fields are not included in the generated TypeScript schema

### ISSUE THREAD

**Issue by mixmav** [dohomi/storyblok-generate-ts#60]
When I add a custom plugin field of, for example, a native color picker, the Blok doesn't include that field in its generated schema at all, even though the JSON returned contains the information.

Is this by design? If not, any suggestions on a workaround would be appreciated. Thanks 🤝

![image](https://github.com/dohomi/storyblok-generate-ts/assets/12530941/1cf1fa6a-9539-4eba-a570-374775572f88)
![image](https://github.com/dohomi/storyblok-generate-ts/assets/12530941/6a73e79e-ff43-40b3-8bcc-52f8a9b34e7e)

**Comment by dohomi** [comment]
everything which is not declared is not rendered, so if you do have a custom plugin you need to extend the type declaration as its not possible to know what the plugin is doing under the hood.

**Comment by mixmav** [comment]
@dohomi Thanks for the quick response! How would I go about extending the type declaration?

Should I create a new custom type, for example `ColorPickerStoryblok`, and manually add it to the `CountdownStoryblok` type definition _after_ importing it? Any way to semi-automate this?

**Comment by dohomi** [comment]
You would declare it anywhere in your project once. There is no other way, either use .d.ts file ending or just import in on your use. You can basically just overwrite any interface with your custom schema
