### ISSUE TITLE
Custom Parser not working?

### ISSUE THREAD

**Issue by combi-35** [dohomi/storyblok-generate-ts#64]
I am trying to resolve default `native-color-picker` type from storyblok with a custom parser.

![Bildschirmfoto 2024-02-20 um 10 45 01](https://github.com/dohomi/storyblok-generate-ts/assets/56366138/ad17bfac-aa3d-43f3-95e4-428c447d858f)

This is my parser:
```
function customParser(key, obj) {
  switch (obj.plugin) {
    case "native-color-picker":
      return {
        [key]: {
          _uid: "string",
          color: "string",
          plugin: "string",
        },
      }
    default:
      return {}
  }
}
```

And here is my script to call everything:
`storyblok-generate-ts source=./components.XXXX.json target=./src/types/component-types-sb customTypeParser=./custom-parser.js`

Unfortunately this does not parse anything for me. Also tried to put everything into a seperate node file but then I also get an error `storyblokToTypescript is not a function`

What am I doing wrong here?
Thanks for help :)

**Comment by dohomi** [comment]
Hi this is an example file of a custom parser, I use it like this for quite some times. 
```js
module.exports = function customTypeParser (key, obj) {
  switch (obj.field_type) {
    case 'bootstrap-utility-class-selector':
      return {
        [key]: {
          type: 'object',
          properties: {
            values: {
              type: 'array',
              items: {
                type: 'string'
              }
            }
          }
        }
      }
    case 'vue-color-picker':
      return {
        [key]: {
          type: 'object',
          properties: {
            rgba: {
              type: 'string'
            }
          }
        }
      }
    case 'material-icons-selector':
      return {
        [key]: {
          type: 'object',
          properties: {
            name: {
              type: 'string'
            }
          }
        }
      }
    default:
      return {}
  }
}

```

**Comment by combi-35** [comment]
I got it working, definitely misunderstood how to use this. But I am curious how you used `obj.field_type`. I cannot find this property in the JSONSchema4 specification.

**Comment by dohomi** [comment]
basically `obj.field_type` will be the name of your custom plugin, probably its `native-color-picker`. With the custom parser you can type the result of that component and that will generate the correct types for your. Its basically a placeholder for custom plugin types where you can define the return type in case values are selected.
