### ISSUE TITLE
Table field type is missing

### ISSUE THREAD

**Issue by wolkyura** [dohomi/storyblok-generate-ts#7]
Hi!

I noticed, that the table field type is missing in generated types, would be great to have `StoryblokTable` type or smth with proper structure, but at least `table: any` would be nice to have

Thank you.

**Comment by dohomi** [comment]
@wolkyura I would accept a PR for integration of tables. Currently I am backed up with work but interested to look into this when time allows.

You can currently set up a custom field for tables as shown in the docs: https://github.com/dohomi/storyblok-generate-ts#example-custom-parser
