### ISSUE TITLE
Link field should use a single type definition

### ISSUE THREAD

**Issue by blindfish3** [dohomi/storyblok-generate-ts#9]
At the moment any component that uses a Link field includes duplicated typings:
```ts
myLinkfield?: 
    | {
        cached_url?: string;
        linktype?: string;
        [k: string]: any;
      }
    | {
        id?: string;
        cached_url?: string;
        linktype?: "story";
        [k: string]: any;
      }
    | {
        url?: string;
        cached_url?: string;
        linktype?: "asset" | "url";
        [k: string]: any;
      }
    | {
        email?: string;
        linktype?: "email";
        [k: string]: any;
      };
```
It would be really nice if this was defined as a separate type (e.g. StoryblokLink) that we could import. For example I've got a separate utility script to parse any link field where I'm going to have to hard-code this type for the time being.

**Comment by dohomi** [comment]
@blindfish3 I am not sure I fully understand your issue here. Do you mind to open a PR that I can review?

**Comment by dohomi** [comment]
As you can see in https://github.com/dohomi/storyblok-generate-ts/blob/master/src/index.js I only parse generic JSON => TypeScript and thus I don't export types except parts which are part of the component definition.

If you want to enter link definitions from a component you simply access them via 
```ts
type CustomComponent = {
  customLink: MyComponentStoryblok['link']
}
```
If that is not sufficient I am happy to review a PR

**Comment by blindfish3** [comment]
TBH I haven't looked at the source yet :sweat_smile: 
But I was working on the assumption that you might be limited by the data you're receiving from the Storyblok CLI ;)
Again - I'll see if I can justify some work time to raise a PR; though this is just a nice-to-have.

**Comment by dohomi** [comment]
Thanks @markus-gx I merged it into the new version
